# Generated by Django 5.1.6 on 2025-04-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('DOB', models.DateField()),
                ('aadhar', models.BigIntegerField()),
                ('pan', models.CharField(max_length=10)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=40)),
                ('acc', models.IntegerField(default=1234567890, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pin', models.IntegerField(null=True)),
            ],
        ),
    ]
