# Generated by Django 5.1.6 on 2025-04-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='aadhar',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='pan',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
