# Generated by Django 5.1.6 on 2025-04-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_account_aadhar_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
