# Generated by Django 5.1.6 on 2025-04-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_account_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='aadhar',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='acc',
            field=models.BigAutoField(default=1234567890, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.IntegerField(default=0),
        ),
    ]
