# Generated by Django 5.1.6 on 2025-04-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_account_aadhar_alter_account_acc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mail',
            field=models.EmailField(default='demofbh@gmail.com', max_length=254),
        ),
    ]
