# Generated by Django 5.1.6 on 2025-04-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_account_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
