# Generated by Django 5.1.6 on 2025-04-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_account_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='aadhar',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='pan',
            field=models.CharField(max_length=10),
        ),
    ]
