# Generated by Django 5.1.6 on 2025-04-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_account_aadhar_alter_account_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='aadhar',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='pan',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
