# Generated by Django 5.1.6 on 2025-04-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_account_aadhar_alter_account_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
